services:
  - type: web
    name: photo-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14